// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace Spotix.Utilities.Models.EFModels;

public partial class AppDbContext : IdentityDbContext<User>
{
	public AppDbContext(DbContextOptions<AppDbContext> options)
		: base(options)
	{
	}

	public virtual DbSet<Area> Areas { get; set; }

	public virtual DbSet<Event> Events { get; set; }

	public virtual DbSet<Order> Orders { get; set; }

	public virtual DbSet<OrderTicket> OrderTickets { get; set; }

	public virtual DbSet<Place> Places { get; set; }

	public virtual DbSet<Session> Sessions { get; set; }

	public virtual DbSet<Ticket> Tickets { get; set; }

	public virtual DbSet<User> Users { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{

		base.OnModelCreating(modelBuilder); // 確保調用基類的 OnModelCreating 方法

		// roles 定義
		//var roles = new List<IdentityRole>
		//{
		//	new IdentityRole { Id = "d7bece5e-cba2-4f5a-a158-2f56919bd43d", ConcurrencyStamp = "d7bece5e-cba2-4f5a-a158-2f56919bd43d", Name = "Admin", NormalizedName = "Admin".ToUpper() },
		//	new IdentityRole { Id = "25935620-161c-4c2f-8936-fe88436ad02c", ConcurrencyStamp = "25935620-161c-4c2f-8936-fe88436ad02c", Name = "User", NormalizedName = "User".ToUpper() }
		//};

		//modelBuilder.Entity<IdentityRole>().HasData(roles);
		// roles 定義

		modelBuilder.Entity<Area>(entity =>
		{
			entity.Property(e => e.Name)
				.IsRequired()
				.HasMaxLength(50);

			entity.HasOne(d => d.Session).WithMany(p => p.Areas)
				.HasForeignKey(d => d.SessionId)
				.HasConstraintName("FK_Areas_Sessions");
		});

		modelBuilder.Entity<Event>(entity =>
		{
			entity.Property(e => e.Host)
				.IsRequired()
				.HasMaxLength(50);
			entity.Property(e => e.ImgUrl).IsRequired();
			entity.Property(e => e.Info).IsRequired();
			entity.Property(e => e.Name)
				.IsRequired()
				.HasMaxLength(50);

			entity.HasOne(d => d.Place).WithMany(p => p.Events)
				.HasForeignKey(d => d.PlaceId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_Events_Places");
		});

		modelBuilder.Entity<Order>(entity =>
		{
			entity.Property(e => e.CreatedTime).HasColumnType("datetime");
			entity.Property(e => e.Number)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Payment)
				.IsRequired()
				.HasMaxLength(50);

			entity.HasOne(d => d.User).WithMany(p => p.Orders)
				.HasForeignKey(d => d.UserId)
				.HasConstraintName("FK_Orders_Users");
		});

		modelBuilder.Entity<OrderTicket>(entity =>
		{
			entity.HasOne(d => d.Order).WithMany(p => p.OrderTickets)
				.HasForeignKey(d => d.OrderId)
				.HasConstraintName("FK_OrderTickets_Orders");

			entity.HasOne(d => d.Ticket).WithMany(p => p.OrderTickets)
				.HasForeignKey(d => d.TicketId)
				.OnDelete(DeleteBehavior.ClientSetNull)
				.HasConstraintName("FK_OrderTickets_Tickets");
		});

		modelBuilder.Entity<Place>(entity =>
		{
			entity.Property(e => e.Name)
				.IsRequired()
				.HasMaxLength(50);
		});

		modelBuilder.Entity<Session>(entity =>
		{
			entity.Property(e => e.AvailableTime).HasColumnType("datetime");
			entity.Property(e => e.Name)
				.IsRequired()
				.HasMaxLength(50);
			entity.Property(e => e.PublishTime).HasColumnType("datetime");
			entity.Property(e => e.SessionTime).HasColumnType("datetime");

			entity.HasOne(d => d.Event).WithMany(p => p.Sessions)
				.HasForeignKey(d => d.EventId)
				.HasConstraintName("FK_Sessions_Events");
		});

		modelBuilder.Entity<Ticket>(entity =>
		{
			entity.Property(e => e.Number)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Reciever).HasMaxLength(100);

			entity.HasOne(d => d.Area).WithMany(p => p.Tickets)
				.HasForeignKey(d => d.AreaId)
				.HasConstraintName("FK_Tickets_Areas");
		});

		modelBuilder.Entity<User>(entity =>
		{
			entity.Property(e => e.Address).HasMaxLength(100);
			entity.Property(e => e.LineId)
				.HasMaxLength(100)
				.HasColumnName("LineID");
		});

		OnModelCreatingPartial(modelBuilder);
	}

	partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}