// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Spotix.Utilities.Models.EFModels;

public partial class Area
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Price { get; set; }

    public int SessionId { get; set; }

    public int Qty { get; set; }

    public int DisplayOrder { get; set; }

    public virtual Session Session { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}