// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Spotix.Utilities.Models.EFModels;

public partial class Event
{
	public int Id { get; set; }

	public string Name { get; set; }

	public string Info { get; set; }

	public string CoverUrl { get; set; }
	public string ImgUrl { get; set; }

	public int PlaceId { get; set; }

	public string Host { get; set; }

	public bool Published { get; set; }

	public virtual Place Place { get; set; }

	public virtual ICollection<Session> Sessions { get; set; } = new List<Session>();
}