// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Spotix.Utilities.Models.EFModels;

public partial class OrderTicket
{
    public int Id { get; set; }

    public int TicketId { get; set; }

    public int OrderId { get; set; }

    public virtual Order Order { get; set; }

    public virtual Ticket Ticket { get; set; }
}