// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Spotix.Utilities.Models.EFModels;

public partial class Place
{
	public int Id { get; set; }

	public string Name { get; set; }

	public int DisplayOrder { get; set; }

	public bool Enabled { get; set; }

	public virtual ICollection<Event> Events { get; set; } = new List<Event>();
}