// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Spotix.Utilities.Models.EFModels;

public partial class Ticket
{
	public int Id { get; set; }

	public int AreaId { get; set; }

	public int RowNumber { get; set; }

	public int SeatNumber { get; set; }

	public string TicketNumber { get; set; }
	public string SessionName { get; set; }

	public bool IsSold { get; set; }

	public bool IsTransfered { get; set; }

	public string RecieverId { get; set; }

	public string SessionName { get; set; }

	public int? OrderId { get; set; }

	public virtual Area Area { get; set; }

	public virtual Order Order { get; set; }

}