// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Spotix.Utilities.Models.EFModels;

public partial class Ticket
{
    public int Id { get; set; }

    public int AreaId { get; set; }

    public int SeatNumber { get; set; }

    public bool SeatSelection { get; set; }

    public string Number { get; set; }

    public bool IsSold { get; set; }

    public bool IsTransfered { get; set; }

    public string Reciever { get; set; }

    public int DisplayOrder { get; set; }

    public virtual Area Area { get; set; }

    public virtual ICollection<OrderTicket> OrderTickets { get; set; } = new List<OrderTicket>();
}