// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace Spotix.Utilities.Models.EFModels;

public partial class User : IdentityUser
{
    //public int Id { get; set; }

    //public string Email { get; set; }

    //public string EncryptedPassword { get; set; }

    //public bool EmailConfirmed { get; set; }

    public string LineId { get; set; }

    //public string UserName { get; set; }

    //public string PhoneNumber { get; set; }

    public bool Gender { get; set; }

    public string Address { get; set; }

    public byte[] AvatarUrl { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}